DROP TABLE IF EXISTS movie;

CREATE TABLE movie (
  imdbID VARCHAR(30) PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  year VARCHAR(4) NOT NULL,
  type VARCHAR(100) NOT NULL,
  poster VARCHAR(2000) NOT NULL
);
